#!/usr/bin/env bash
# Generated by the /wizard skill. The shared library below is intentionally
# kept identical to the skill template.
set -euo pipefail

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}
say() { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if command -v wslview >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}
pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"; else printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"; fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then WRITTEN_SECRET+=("$name"); printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"; return; fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"; return; fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then printf '\n'; warn "still to do by hand:"; for s in "${SKIPPED[@]}"; do note "  - $s"; done; fi
  printf '\n'
}

# STAGES
TOTAL_STAGES=3
INFRASTRUCTURE_DIR="${INFRASTRUCTURE_DIR:-../cannyboiz-devops-hub/terraform/ez-dk-citizen}"

banner "AWS S3 setup for ez-dk-citizen"

stage "Apply the reviewed S3 boundary"
say "This applies only the prepared sibling Terraform change; it creates no access keys and stores no secrets in state."
open_url "https://console.aws.amazon.com/s3/home?region=eu-north-1#buckets"
step "Review the private bucket, public-access block, CORS origins, and conditional-write policy in the AWS console."
step "From another terminal, run: terraform -chdir=$INFRASTRUCTURE_DIR init && terraform -chdir=$INFRASTRUCTURE_DIR plan"
if confirm "Apply that reviewed Terraform plan now"; then
  terraform -chdir="$INFRASTRUCTURE_DIR" apply
else
  warn "Terraform was not applied. Re-run this wizard after the infrastructure change is applied."
fi

stage "Create or rotate the dedicated IAM access key"
say "Use only the ez-dk-citizen-app IAM user. Do not create an IAM key through Terraform."
open_url "https://console.aws.amazon.com/iam/home#/users/ez-dk-citizen-app?section=security_credentials"
step "Under Access keys, create a new key for Local code, or create a replacement before deactivating the old key."
step "Copy the access-key ID and secret now; AWS shows the secret only once."
ask_secret AWS_ACCESS_KEY_ID "Paste the new AWS access-key ID:"
ask_secret AWS_SECRET_ACCESS_KEY "Paste the new AWS secret access key:"
step "After this wizard and a successful live tracer, deactivate the replaced key and delete it after the rotation window."

stage "Save local runtime secrets"
say "Values are written only to $ENV_FILE, which must be an ignored .env file. No GitHub secret is configured because this repository has no deployment workflow."
ask AWS_REGION "AWS region:"; AWS_REGION="${AWS_REGION:-eu-north-1}"
ask S3_BUCKET "S3 bucket:"; S3_BUCKET="${S3_BUCKET:-ez-dk-citizen-audio}"
write_env AWS_REGION "$AWS_REGION"
write_env S3_BUCKET "$S3_BUCKET"
write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
note "For deployment, enter these same four names directly in its host-only secret store; never commit a deployment env file."

finish
